name: api_work
description: A new Flutter project.
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # SQLite database
  sqflite: ^2.3.0

  # Path provider for database path
  path: ^1.8.3

  # API handling
  http: 1.3.0

  # Enhanced DataTable UI
  data_table_2: ^2.3.2

  # State management (optional, for future scaling)
  provider: ^6.1.2

  # JSON serialization (optional, for cleaner models)
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation (if using json_serializable in future)
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Uncomment and add assets/fonts when needed
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
